### Get report
GET http://localhost:3000/reports?maker=Honda&model=Civic&year=2015&mileage=120000&lng=0&lat=0

### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "maker": "Honda",
  "model": "Civic",
  "year": 2015,
  "mileage": 120000,
  "lng": 0,
  "lat": 0,
  "price": 5000
}

### Approve report
POST http://localhost:3000/reports/approve/1
