### Who am I
GET http://localhost:3000/auth/whoami

### Create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### Log in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### Sign out
POST http://localhost:3000/auth/signout

### Find user by id
GET http://localhost:3000/auth/2

### Get isers by email
GET http://localhost:3000/auth?email=a@b.cd

### Delete user bu id
DELETE http://localhost:3000/auth/1

### Update user by id
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "a@b.cd"
}
