### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "maker": "Honda",
  "model": "Civic",
  "year": 2015,
  "mileage": 120000,
  "lng": 0,
  "lat": 0,
  "price": 5000
}

### Check Admin Guard
GET http://localhost:3000/reports
